server:
  port: 8080

spring:
  application:
    name: content-calendar
  datasource:
    generate-unique-name: false
    name: content-db

  h2.console.enabled: true

logging:
  level:
    org.springframework.jdbc: DEBUG

cc:
  welcome1: "welcome message 1"
  welcome3: "Not the default value welcome"
