server:
  port: 8080

spring:
  application:
    name: content-calendar
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password

  sql.init.mode: always

  profiles:
    active: dev

logging:
  level:
    org.springframework.jdbc: DEBUG


cc:
  welcome1: "welcome message 1"
  welcome3: "Not the default value welcome"
  city1: Tokyo
  city2: Kyoto

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
