### Find all content
GET http://localhost:8080/api/content

### Get content by id
GET http://localhost:8080/api/content/1

### Create content
POST http://localhost:8080/api/content
Content-Type: application/json

{
  "desc": "desc another blog post",
  "status": "IN_PROGRESS",
  "contentType": "ARTICLE",
  "dateCreated": "2024-07-10T18:56:01.254479085",
  "dateUpdated": null,
  "url": ""
}

### Update content
PUT http://localhost:8080/api/content/1
Content-Type: application/json

{
  "id": 1,
  "title": "Blog Post 1",
  "desc": "Blog post 1",
  "status": "IDEA",
  "contentType": "ARTICLE",
  "dateCreated": "2024-07-10T18:56:01.254479085",
  "dateUpdated":"2024-07-10T19:56:01.254479085",
  "url": "http://localhost:8080/blah-blah"
}
